version: '3.8'

services:
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
    php-fpm:
        container_name: hutka_php
        environment:
            PHP_IDE_CONFIG: "serverName=hutka_php"
        build:
            dockerfile: docker/php/Dockerfile
            context: .
        volumes:
            - ./:/var/www/html
        networks:
            - app-network
    mysql:
        container_name: hutka_db
        image: mariadb:10.3
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wd05
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - app-network
    react:
        build:
            context: ./react
        container_name: react
        ports:
            - "3000:3000"
        volumes:
            - ./src:/app/src
            - ./public:/app/public
            - /app/node_modules:/app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
