version: '3.8'

services:
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
            - mysql
    php-fpm:
        container_name: hutka_php
        environment:
            PHP_IDE_CONFIG: "serverName=hutka_php"
        build:
            dockerfile: docker/php/Dockerfile
            context: .
        volumes:
            - ./:/var/www/html
        links:
            - mysql
    mysql:
        container_name: hutka_db
        image: mariadb:10.3
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wd05
